{
 "title": "Netology Copy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg by(instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[$__interval])) * 100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU-LA-1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU-LA-5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU-LA-15",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "FileSpace Used",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "100-(100-((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})/(1024^2)",
     "legendFormat": "RAM FREE"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})/(1024^2)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) / ( 1024^2)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}