---
- name: Restart Vector
  become: "{{ 'false' if ansible_user_uid == 0 else 'true' }}"
  ignore_errors: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
    enabled: yes
    daemon_reload: true
  tags:
    - vector